We tried to update hibernate-core up to 5.4.10.Final. Changed dependency and updated CustomHibernateServiceImpl, UserTransactionJtaPlatform in order to fit the new hibernate, but we ran into problems (java.lang.NoClassDefFoundError: org/hibernate/service/ServiceRegistryBuilder at org.exoplatform.services.database.impl.HibernateConfigurationImpl.buildSessionFactory(HibernateConfigurationImpl.java:48)). Then we tried to update exo.core.component.database.HibernateConfigurationImpl, but unforchantly, stalled due to lack of needed classes (didn't find a replacement for them (org.hibernate.cache.spi.GeneralDataRegion, org.hibernate.cache.spi.EntityRegion, org.hibernate.cache.spi.NaturalIdRegion, org.hibernate.cache.spi.CollectionRegion, org.hibernate.cache.spi.CacheDataDescription, org.hibernate.cache.spi.access.EntityRegionAccessStrategy)).